### PR TITLE
add StringsIntersection and IntsIntersection

### PR DESCRIPTION
**Pull request by dorissun**

### CODE REVIEW

**Comment by cortex** [comment]
Both implementations looks solid. They could be further optimized by initializing the start set with the smaller of needle and  haystack instead of always starting with the haystack. the names kind of implies that there are more entries in the haystack, but it is optimized in the reverse.

I am also not entirely sure it was a good idea to make this a separate library, these functions are so small that they would be no problem to have in the repository that needs them.

**Comment by cortex** [comment]
It would be good if we had unit tests for these!

**Comment by dorissun** [comment]
For the intersection check, I am not sure we should enforce the haystack to be a larger slice than needles. They are simply two slices. I think I would modify the argument names so that they don't indicate the sizes.

**Comment by dorissun** [comment]
I think it makes sense to have a library to do set operations internally, but we don't need to force it. If someone likes to include these tiny functions in the feature repo, they can do it. For those who wants to call these helper functions in this library might love to have a central place where they can view and optimize it.

**Comment by dorissun** [comment]
I just added unittest for this repo.

**Comment by cortex** [comment]
Looks great! :+1:

**Pull request merged**
